import 'package:finance_manager/data/models/currency.dart';

final List<Currency> currencyList = [
  Currency(code: 'USD', name: 'US Dollar'),
  Currency(code: 'EUR', name: 'Euro'),
  Currency(code: 'IRR', name: 'Iranian Rial'),
  Currency(code: 'GBP', name: 'British Pound'),
  Currency(code: 'JPY', name: 'Japanese Yen'),
  Currency(code: 'CHF', name: 'Swiss Franc'),
  Currency(code: 'CAD', name: 'Canadian Dollar'),
  Currency(code: 'AUD', name: 'Australian Dollar'),
  Currency(code: 'NZD', name: 'New Zealand Dollar'),
  Currency(code: 'CNY', name: 'Chinese Yuan'),
  Currency(code: 'SEK', name: 'Swedish Krona'),
  Currency(code: 'NOK', name: 'Norwegian Krone'),
  Currency(code: 'DKK', name: 'Danish Krone'),
  Currency(code: 'INR', name: 'Indian Rupee'),
  Currency(code: 'RUB', name: 'Russian Ruble'),
  Currency(code: 'BRL', name: 'Brazilian Real'),
  Currency(code: 'ZAR', name: 'South African Rand'),
  Currency(code: 'MXN', name: 'Mexican Peso'),
  Currency(code: 'SGD', name: 'Singapore Dollar'),
  Currency(code: 'HKD', name: 'Hong Kong Dollar'),
  Currency(code: 'KRW', name: 'South Korean Won'),
  Currency(code: 'TRY', name: 'Turkish Lira'),
  Currency(code: 'SAR', name: 'Saudi Riyal'),
  Currency(code: 'AED', name: 'UAE Dirham'),
  Currency(code: 'EGP', name: 'Egyptian Pound'),
  Currency(code: 'THB', name: 'Thai Baht'),
  Currency(code: 'PLN', name: 'Polish Zloty'),
  Currency(code: 'CZK', name: 'Czech Koruna'),
  Currency(code: 'MYR', name: 'Malaysian Ringgit'),
  Currency(code: 'IDR', name: 'Indonesian Rupiah'),
  Currency(code: 'PKR', name: 'Pakistani Rupee'),
  Currency(code: 'TWD', name: 'Taiwan Dollar'),
];

final Map<String, double> exchangeRates = {
  'USD': 1.0,
  'EUR': 0.91,
  'IRR': 42000,
  'GBP': 0.78,
  'JPY': 156.5,
  'CHF': 0.9,
  'CAD': 1.36,
  'AUD': 1.5,
  'NZD': 1.63,
  'CNY': 7.24,
  'SEK': 10.78,
  'NOK': 10.6,
  'DKK': 6.8,
  'INR': 83.2,
  'RUB': 91.5,
  'BRL': 5.14,
  'ZAR': 18.0,
  'MXN': 16.8,
  'SGD': 1.34,
  'HKD': 7.82,
  'KRW': 1350.0,
  'TRY': 32.2,
  'SAR': 3.75,
  'AED': 3.67,
  'EGP': 47.0,
  'THB': 36.7,
  'PLN': 4.0,
  'CZK': 23.1,
  'MYR': 4.7,
  'IDR': 16000.0,
  'PKR': 278.0,
  'TWD': 32.3,
};

extension CurrencyCodeExtension on String {
  Currency toCurrency() {
    return currencyList.firstWhere(
      (currency) => currency.code == this,
      orElse: () => Currency(code: 'USD', name: 'US Dollar'),
    );
  }
}
